### ISSUE TITLE
Deprecate dataset description <https://doi.org/10.6069/uwlib.55.a>, dataset <https://doi.org/10.6069/uwlib.55.a#uwSemWeb>

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/uwlswd_datasets#22]
A starting point from https://github.com/uwlib-cams/uwlswd/discussions/42

> (2) How do we deprecate https://doi.org/10.6069/uwlib.55.a#uwSemWeb and https://doi.org/10.6069/uwlib.55.a ? I suspect we just leave it in place and strip-out false or redundant triples. Then those resources would not be incorrect (unless we add to the "partitions" in ways that contradict the assertions in uwlib.55.a and uwlib.55.a#uwSemWeb), so who are they hurting? Maybe us, as we'd have to manage the DOI, but I bet we can live with that.

**Comment by briesenberg07** [comment]
📓 NOTE on uwlswd/py/datacite_metadata.py + VoID file

```
====================
Generating DataCite metadata file from ../uwlswd_datasets/void/void_description_of_the_dataset_university_of_washington_libraries_semantic_web_data.rdf
====================
Type error at char 28 in expression in xsl:result-document/@href on line 12 column 47 of rdf2datacite.xsl:
  XPTY0004  A sequence of more than one item is not allowed as the first argument of
  fn:substring-after() ("https://doi.org/10.6069/uwlib.55.a",
  "https://doi.org/10.6069/uwlib.55.a.3.6")
  In template rule with match="/" on line 8 of rdf2datacite.xsl
A sequence of more than one item is not allowed as the first argument of fn:substring-after() ("https://doi.org/10.6069/uwlib.55.a", "https://doi.org/10.6069/uwlib.55.a.3.6")
```

**Comment by briesenberg07** [comment]
Still to do for ***short term title and description fix***

- [ ] Confirm [new title and description](https://github.com/uwlib-cams/uwlswd_datasets/commit/3ce7340b2e9ba231e5497e5c80f4025bc98884a6) OK
- [ ] Check over manual edits to HTML, including new schema markup - see f7827d8 > .html diff
- [ ] (BONUS: Delete `owl:version` triples from RDF/XML + rows from HTML - not part of the title/description changes but owl:version, with now-out-of-date version numbers, need to go)
- [ ] Confirm updated (minimal) DataCite metadata OK - see [uwlswd commit a639b1f](https://github.com/uwlib-cams/uwlswd/commit/a639b1fff3b02cba7b59fe983a357a55f4763634)
- [ ] Make and merge pull request
- [ ] Update DataCite XML ***and URL***

**Comment by briesenberg07** [comment]
# starting over
for the sake of easier-to-compare diffs for these manual changes

# to-do list
for ***short term title and description fix***

- [ ] ~~Confirm [new title and description](https://github.com/uwlib-cams/uwlswd_datasets/commit/3ce7340b2e9ba231e5497e5c80f4025bc98884a6) OK~~ I'll put this in the pull request for confirmation
- [ ] Make/check manual edits to HTML, including new schema markup - see f7827d8 > .html diff
   - [ ] dct:title for DOI, DOI\#fragment
   - [ ] Replace links to data in washington.edu/static with links to github.io
   - [ ] Fix resource title in footer
   - [ ] Fix link 'JSON' > 'JSON-LD'
   - [ ] Add missing `html/head/link` resources
   - [ ] Fix URLs for `html/head/link` resources
   - [ ] (BONUS: Delete `owl:version` triples from RDF/XML + rows from HTML - not part of the title/description changes but owl:version, with now-out-of-date version numbers, need to go)
   - [ ] ... many changes in https://github.com/uwlib-cams/uwlswd_datasets/commit/f7827d88747231464f65d0f877820e5600db7ecb lost in noise of format/indent changes...
- [ ] Make/check manual edits to RDF/XML
   - [ ] (BONUS: Delete `owl:version` triples from RDF/XML + rows from HTML - not part of the title/description changes but owl:version, with now-out-of-date version numbers, need to go)
   - [ ] dct:title for DOI, DOI\#fragment
   - [ ] Replace links to data in washington.edu/static with links to github.io
   - [ ] Add JSON-LD to each dct:hasFormat set
- [ ] Confirm updated (minimal) DataCite metadata OK - see [uwlswd commit a639b1f](https://github.com/uwlib-cams/uwlswd/commit/a639b1fff3b02cba7b59fe983a357a55f4763634)
- [ ] Make pull request 
- [ ] Merge pull request / update DataCite XML and URL
- [ ] Consider removing VoID description from uwlswd/index.html

**Comment by briesenberg07** [comment]
# [STOPGAP MEASURES](https://github.com/uwlib-cams/uwlswd_datasets/issues/22#issuecomment-1850915944) COMPLETE ✅
